#!/usr/bin/env bash
# This script displays all listening ports with their associated PID and program name
# -t = affiche les ports TCP, -u = affiche les ports UDP, -l les ports en écoute, (LISTEN), -x = inclut les UNIX Sockets,
# -n = Affiche les adresses et ports sous forme numérique (pas de résolution DNS) (plus rapide), -p = affiche le PID + programme associé

sudo netstat -tulxnp
